/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Greeter__factory } from "./Greeter__factory";
export { TinyVillage__factory } from "./TinyVillage__factory";
